### ISSUE TITLE
Please don't remove the fill attribute in svg

### ISSUE THREAD

**Issue by ganlanyuan** [w0rm/gulp-svgstore#81]
Hey,
Original svg code:
```html
<svg viewBox="0 0 806 806" xmlns="http://www.w3.org/2000/svg" fill="#fff">
```
Sprite svg:
```html
<symbol id="us" viewBox="0 0 806 806">
```
Gulp option:
```javascript
.pipe(svgstore({ inlineSvg: true }))
```
The `fill` attribute is removed. Is there a way to prevent this happen?

**Comment by dotmagic** [comment]
@ganlanyuan Why you need this attribute? It's much better to use CSS!
`.icons { fill: #fff; }`

**Comment by ganlanyuan** [comment]
I'm using some icons which I downloaded previously.
Off course I can add the background-color manually, but consider If I have 100 icons with different fill color, how can I possibly manage them.
I expect gulp-svgstore just combine them together, don't remove the icons' original attribute.
Thanks anyway for the great plugin!

**Comment by w0rm** [comment]
@ganlanyuan you can always pipe through gulp-cheerio and automate it.

**Comment by ganlanyuan** [comment]
@w0rm Thanks 
I moved the fill attribute from the `<svg>` to a new created top level `<g>` tag and then I run the gulp sprite command, got this error:
```
$symbol.append($svg.contents())
                        ^

TypeError: $svg.contents is not a function
    at Transform.transform [as _transform] (/Users/linwilliam/Documents/Projects/develop/icons/node_modules/gulp-svgstore/index.js:112:25)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Transform.Writable.write (_stream_writable.js:220:11)
    at write (/Users/linwilliam/Documents/Projects/develop/icons/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/linwilliam/Documents/Projects/develop/icons/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/linwilliam/Documents/Projects/develop/icons/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:86:13)
```
Is this related to the modification of the svg file?

**Comment by w0rm** [comment]
@ganlanyuan sorry but this information is not enough to figure out the problem. Can you provide the svg file that does not work or a test project that reproduces the issue?

**Comment by ganlanyuan** [comment]
Package.json
```javascript
"devDependencies": {
  "gulp": "^3.9.1",
  "gulp-cheerio": "^0.6.2",
  "gulp-rename": "^1.2.2",
  "gulp-svgstore": "^6.1.0"
}
```
gulpfile.js
```javascript
var gulp = require('gulp');
var svgstore = require('gulp-svgstore');
var rename = require('gulp-rename');

gulp.task('sprites', function () {
  return gulp.src(['svg-min/fill/eye-fill.svg'])
    .pipe(svgstore({ inlineSvg: true }))
    .pipe(rename('sprites.svg'))
    .pipe(gulp.dest(''));
});
```
eye-fill.svg
```svg
<svg width="48" height="48" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg"><title>eye-fill</title><path d="M24 9C10 9 .5 24 .5 24S10 39 24 39s23.5-15 23.5-15S38 9 24 9zm0 23a8 8 0 1 0 0-16 8 8 0 0 0 0 16z" fill="currentColor" fill-rule="evenodd"></path></svg>
```
And I got this error
```
/Users/linwilliam/Documents/Projects/develop/icons/node_modules/gulp-svgstore/index.js:112
    $symbol.append($svg.contents())
                        ^

TypeError: $svg.contents is not a function
    at Transform.transform [as _transform] (/Users/linwilliam/Documents/Projects/develop/icons/node_modules/gulp-svgstore/index.js:112:25)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Transform.Writable.write (_stream_writable.js:220:11)
    at write (/Users/linwilliam/Documents/Projects/develop/icons/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/linwilliam/Documents/Projects/develop/icons/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/linwilliam/Documents/Projects/develop/icons/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:86:13)
```

**Comment by w0rm** [comment]
This works for me:

```
var gulp = require('gulp');
var svgstore = require('gulp-svgstore');

gulp.task('default', function () {
  return gulp.src('svg-min/fill/eye-fill.svg')
    .pipe(svgstore({ inlineSvg: true }))
    .pipe(gulp.dest('.'));
});
```

your example was output in the same directory as the source files.

**Comment by ganlanyuan** [comment]
Hmm, I get the same error even I updated the `gulp.dest`.

**Comment by w0rm** [comment]
Can you give the exact code that you run? You can zip it or create a project on github

**Comment by ganlanyuan** [comment]
After I delete the `node_modules/` folder and reinstall everything, the error disappeared.
Thanks a lot for your help!

**Comment by w0rm** [comment]
@ganlanyuan cool that you figured this!

**Comment by thesayyn** [comment]
Im facing with this issue also. it's useless, there should be option for remove it or not. i have bunch of svg icon how i can recolor all of them.

**Comment by f1eeman** [comment]
Hey,
Original svg code:
```
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="20" viewBox="0 0 32 20">
<path d="M29,0H3C1.35,0,0,1.35,0,3v14c0,1.65,1.35,3,3,3h26c1.65,0,3-1.35,3-3V3C32,1.35,30.65,0,29,0z M14.403,15.854c-0.545,0.108-1.104,0.164-1.678,0.164c-0.694,0-1.354-0.107-1.976-0.323c-0.623-0.214-1.172-0.562-1.646-1.041 s-0.852-1.103-1.133-1.868C7.69,12.02,7.551,11.091,7.551,10c0-1.134,0.157-2.085,0.471-2.851c0.315-0.768,0.723-1.384,1.224-1.854  c0.502-0.468,1.062-0.804,1.679-1.008c0.616-0.204,1.233-0.307,1.852-0.307c0.66,0,1.22,0.045,1.678,0.134  c0.457,0.087,0.835,0.192,1.133,0.313L15.14,6.347c-0.254-0.121-0.555-0.209-0.902-0.265C13.891,6.027,13.47,6,12.973,6 c-0.915,0-1.649,0.325-2.206,0.977c-0.558,0.651-0.836,1.663-0.836,3.031c0,0.598,0.067,1.142,0.199,1.632  c0.132,0.493,0.334,0.913,0.603,1.26c0.271,0.349,0.607,0.619,1.01,0.812c0.402,0.193,0.867,0.29,1.396,0.29  c0.496,0,0.915-0.049,1.257-0.148c0.342-0.099,0.639-0.227,0.893-0.38l0.463,1.841C15.398,15.564,14.949,15.745,14.403,15.854z   M23.101,15.854c-0.545,0.108-1.105,0.164-1.678,0.164c-0.694,0-1.354-0.107-1.976-0.323c-0.623-0.214-1.172-0.562-1.646-1.041  s-0.852-1.103-1.133-1.868c-0.281-0.767-0.421-1.695-0.421-2.786c0-1.134,0.157-2.085,0.471-2.851  c0.314-0.768,0.723-1.384,1.223-1.854c0.502-0.468,1.062-0.804,1.68-1.008c0.616-0.204,1.233-0.307,1.851-0.307 c0.661,0,1.221,0.045,1.678,0.134c0.458,0.087,0.836,0.192,1.133,0.313l-0.446,1.918c-0.253-0.121-0.554-0.209-0.901-0.265  C22.588,6.027,22.166,6,21.67,6c-0.915,0-1.649,0.325-2.206,0.977c-0.558,0.651-0.836,1.663-0.836,3.031  c0,0.598,0.067,1.142,0.199,1.632c0.132,0.493,0.334,0.913,0.603,1.26c0.271,0.349,0.606,0.619,1.009,0.812 c0.402,0.193,0.868,0.29,1.396,0.29c0.497,0,0.915-0.049,1.257-0.148c0.342-0.099,0.64-0.227,0.894-0.38l0.463,1.841  C24.096,15.564,23.646,15.745,23.101,15.854z"/>
</svg>
```
Sprite svg:
```
<symbol id="icon-video-subtitles" viewBox="0 0 32 20"><path d="M29,0H3C1.35,0,0,1.35,0,3v14c0,1.65,1.35,3,3,3h26c1.65,0,3-1.35,3-3V3C32,1.35,30.65,0,29,0z M14.403,15.854c-0.545,0.108-1.104,0.164-1.678,0.164c-0.694,0-1.354-0.107-1.976-0.323c-0.623-0.214-1.172-0.562-1.646-1.041 s-0.852-1.103-1.133-1.868C7.69,12.02,7.551,11.091,7.551,10c0-1.134,0.157-2.085,0.471-2.851c0.315-0.768,0.723-1.384,1.224-1.854  c0.502-0.468,1.062-0.804,1.679-1.008c0.616-0.204,1.233-0.307,1.852-0.307c0.66,0,1.22,0.045,1.678,0.134  c0.457,0.087,0.835,0.192,1.133,0.313L15.14,6.347c-0.254-0.121-0.555-0.209-0.902-0.265C13.891,6.027,13.47,6,12.973,6 c-0.915,0-1.649,0.325-2.206,0.977c-0.558,0.651-0.836,1.663-0.836,3.031c0,0.598,0.067,1.142,0.199,1.632  c0.132,0.493,0.334,0.913,0.603,1.26c0.271,0.349,0.607,0.619,1.01,0.812c0.402,0.193,0.867,0.29,1.396,0.29  c0.496,0,0.915-0.049,1.257-0.148c0.342-0.099,0.639-0.227,0.893-0.38l0.463,1.841C15.398,15.564,14.949,15.745,14.403,15.854z   M23.101,15.854c-0.545,0.108-1.105,0.164-1.678,0.164c-0.694,0-1.354-0.107-1.976-0.323c-0.623-0.214-1.172-0.562-1.646-1.041  s-0.852-1.103-1.133-1.868c-0.281-0.767-0.421-1.695-0.421-2.786c0-1.134,0.157-2.085,0.471-2.851  c0.314-0.768,0.723-1.384,1.223-1.854c0.502-0.468,1.062-0.804,1.68-1.008c0.616-0.204,1.233-0.307,1.851-0.307 c0.661,0,1.221,0.045,1.678,0.134c0.458,0.087,0.836,0.192,1.133,0.313l-0.446,1.918c-0.253-0.121-0.554-0.209-0.901-0.265  C22.588,6.027,22.166,6,21.67,6c-0.915,0-1.649,0.325-2.206,0.977c-0.558,0.651-0.836,1.663-0.836,3.031  c0,0.598,0.067,1.142,0.199,1.632c0.132,0.493,0.334,0.913,0.603,1.26c0.271,0.349,0.606,0.619,1.009,0.812 c0.402,0.193,0.868,0.29,1.396,0.29c0.497,0,0.915-0.049,1.257-0.148c0.342-0.099,0.64-0.227,0.894-0.38l0.463,1.841  C24.096,15.564,23.646,15.745,23.101,15.854z"/>
</symbol>
```

At first glance, everything is fine....

svg code in browser inserted via tag <include>:

`<svg id="icon-video-subtitles"><path _**fill="#454545"**_ d="M29 0H3C1.35 0 0 1.35 0 3v14c0 1.65 1.35 3 3 3h26c1.65 0 3-1.35 3-3V3c0-1.65-1.35-3-3-3zM14.403 15.854a8.61 8.61 0 01-1.678.164 5.986 5.986 0 01-1.976-.323c-.623-.214-1.172-.562-1.646-1.041s-.852-1.103-1.133-1.868c-.28-.766-.419-1.695-.419-2.786 0-1.134.157-2.085.471-2.851.315-.768.723-1.384 1.224-1.854a4.53 4.53 0 011.679-1.008 5.86 5.86 0 011.852-.307c.66 0 1.22.045 1.678.134.457.087.835.192 1.133.313l-.448 1.92a3.332 3.332 0 00-.902-.265A8.244 8.244 0 0012.973 6c-.915 0-1.649.325-2.206.977-.558.651-.836 1.663-.836 3.031 0 .598.067 1.142.199 1.632.132.493.334.913.603 1.26.271.349.607.619 1.01.812.402.193.867.29 1.396.29.496 0 .915-.049 1.257-.148.342-.099.639-.227.893-.38l.463 1.841c-.354.249-.803.43-1.349.539zm8.698 0a8.618 8.618 0 01-1.678.164 5.986 5.986 0 01-1.976-.323c-.623-.214-1.172-.562-1.646-1.041s-.852-1.103-1.133-1.868c-.281-.767-.421-1.695-.421-2.786 0-1.134.157-2.085.471-2.851.314-.768.723-1.384 1.223-1.854a4.526 4.526 0 011.68-1.008 5.858 5.858 0 011.851-.307c.661 0 1.221.045 1.678.134a6.05 6.05 0 011.133.313l-.446 1.918a3.314 3.314 0 00-.901-.265A8.569 8.569 0 0021.67 6c-.915 0-1.649.325-2.206.977-.558.651-.836 1.663-.836 3.031 0 .598.067 1.142.199 1.632.132.493.334.913.603 1.26.271.349.606.619 1.009.812.402.193.868.29 1.396.29.497 0 .915-.049 1.257-.148.342-.099.64-.227.894-.38l.463 1.841c-.353.249-.803.43-1.348.539z"></path></svg>`

Why did the "fill" appear in the browser?

Thank you...
